name: DEPLOY_ON_RELEASE

on:
  release:
    types: [released]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [15.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Save build in /var/www/contentpedia_prod
        run: cp -r /root/completed_build/* /var/www/contentpedia_prod
